---
abstract: 'Simple Interface to Instagram oAuth API'
author:
  - 'Daya Sagar Nune <dayanune@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Instagram
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  Test::More: 0
  URI: 0
  strict: 0
  warnings: 0
version: 0.04
